#!/bin/bash
# =============================================================================
# 10.5 EdgeTPU Model Compilation for EfficientNet-B3 and ResNet50
#
# Compiles INT8 TFLite models for Google Coral EdgeTPU.
# Produces *_edgetpu.tflite variants.
#
# Prerequisites:
#   - edgetpu_compiler installed (https://coral.ai/docs/edgetpu/compiler/)
#   - INT8 quantized TFLite models in export/
#     (generated by 10.3 and 10.4 scripts)
#
# Usage:
#   bash scripts/10.5_compile_edgetpu_efficientnet_resnet50.sh
# =============================================================================

set -e

EXPORT_DIR="export"

echo "=============================================="
echo "10.5 EdgeTPU Compilation: EfficientNet + ResNet50"
echo "=============================================="

# Check compiler availability
if ! command -v edgetpu_compiler &> /dev/null; then
    echo "[ERROR] edgetpu_compiler not found."
    echo "Install from: https://coral.ai/docs/edgetpu/compiler/"
    echo ""
    echo "On Debian/Ubuntu:"
    echo "  curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -"
    echo "  echo 'deb https://packages.cloud.google.com/apt coral-edgetpu-stable main' | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list"
    echo "  sudo apt update && sudo apt install edgetpu-compiler"
    exit 1
fi

edgetpu_compiler --version

# Models to compile
# NOTE: EfficientNet-B3 is NOT EdgeTPU-compatible due to Swish activation
# (LOGISTIC + broadcast MUL in squeeze-excitation blocks). The EdgeTPU
# compiler cannot map these operations. Only ResNet50 is compiled here.
MODELS=(
    "resnet50_int8_ptq_hybrid"
    "resnet50_int8_ptq_Fuzzy"
    "resnet50_int8_ptq_sbert"
)

echo ""
echo "Models to compile:"
for model in "${MODELS[@]}"; do
    echo "  - ${model}.tflite"
done
echo ""

COMPILED=0
FAILED=0

for model in "${MODELS[@]}"; do
    INPUT="${EXPORT_DIR}/${model}.tflite"

    if [ ! -f "${INPUT}" ]; then
        echo "[WARN] Model not found: ${INPUT} -- skipping"
        ((FAILED++)) || true
        continue
    fi

    echo "----------------------------------------------"
    echo "Compiling: ${model}"
    echo "----------------------------------------------"

    # edgetpu_compiler outputs to the same directory as input by default
    # Use -o to control output directory
    edgetpu_compiler -o "${EXPORT_DIR}" "${INPUT}"

    OUTPUT="${EXPORT_DIR}/${model}_edgetpu.tflite"

    if [ -f "${OUTPUT}" ]; then
        SIZE_MB=$(du -h "${OUTPUT}" | cut -f1)
        echo "[OK] ${OUTPUT} (${SIZE_MB})"
        ((COMPILED++)) || true
    else
        echo "[ERROR] Compilation failed for ${model}"
        ((FAILED++)) || true
    fi
    echo ""
done

echo "=============================================="
echo "Summary"
echo "=============================================="
echo "Compiled: ${COMPILED}"
echo "Failed:   ${FAILED}"
echo ""

if [ ${COMPILED} -gt 0 ]; then
    echo "EdgeTPU models in: ${EXPORT_DIR}/"
    echo ""
    echo "EfficientNet models:"
    ls -la "${EXPORT_DIR}"/efficientnet_int8_ptq_*_edgetpu.tflite 2>/dev/null || echo "  (none)"
    echo ""
    echo "ResNet50 models:"
    ls -la "${EXPORT_DIR}"/resnet50_int8_ptq_*_edgetpu.tflite 2>/dev/null || echo "  (none)"
fi

exit ${FAILED}
